# 服务配置
server:
  port: 8080

spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:8080
        instance:
          name: jprool
          service-url: http://127.0.0.1:8080
        username: admin
        password: admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

# 代理业务配置
proxy:
  tunnel: 8887
  # 代理池配置
  pool:
    # 代理池初始大小
    init-capacity: 1000
  # 代理供应商配置
  provider:
    # 获取供应商代理线程池大小
    pool-size: 2
